services:
    mysql:
        image: 'mysql:5.7.41'
        environment:
            MYSQL_ROOT_PASSWORD: dbpassword
            MYSQL_DATABASE: beerservice
        ports:
          - '3306'    
        #command: ['mysqld', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci']
        healthcheck:
          test: [ "CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-pdbpassword" ]
          interval: 10s
          timeout: 5s
          retries: 5
          
    jms:
        image: apache/activemq-artemis:2.39.0
        ports:
            - 8161:8161
            - 61616:61616   
        environment:
          ARTEMIS_USER: artemis
          ARTEMIS_PASSWORD: simetraehcapa
        healthcheck:
          test: [ "CMD", "curl", "-f", "http://localhost:8161" ]
          interval: 10s
          timeout: 5s
          retries: 5      













