services:
  mysql:
    container_name: mysql
    image: 'mysql:8.4.7'
    environment:
      MYSQL_ROOT_PASSWORD: dbpassword
      MYSQL_DATABASE: beerservice
    ports:
      - '3306:3306'
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-pdbpassword" ]
      interval: 10s
      timeout: 5s
      retries: 5
  
  jms:
    container_name: jms
    image: apache/activemq-artemis:2.43.0
    ports:
      - 8161:8161
      - 61616:61616
    environment:
      ARTEMIS_USER: artemis
      ARTEMIS_PASSWORD: simetraehcapa
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8161" ]
      interval: 10s
      timeout: 5s
      retries: 5      













